/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizerRouteImport } from './routes/visualizer'
import { Route as QaRouteImport } from './routes/qa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualizerIndexRouteImport } from './routes/visualizer.index'
import { Route as VisualizerRunIdRouteImport } from './routes/visualizer.$runId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const VisualizerRoute = VisualizerRouteImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizerIndexRoute = VisualizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VisualizerRoute,
} as any)
const VisualizerRunIdRoute = VisualizerRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => VisualizerRoute,
} as any).lazy(() =>
  import('./routes/visualizer.$runId.lazy').then((d) => d.Route),
)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qa': typeof QaRoute
  '/visualizer': typeof VisualizerRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/visualizer/$runId': typeof VisualizerRunIdRoute
  '/visualizer/': typeof VisualizerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qa': typeof QaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/visualizer/$runId': typeof VisualizerRunIdRoute
  '/visualizer': typeof VisualizerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qa': typeof QaRoute
  '/visualizer': typeof VisualizerRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/visualizer/$runId': typeof VisualizerRunIdRoute
  '/visualizer/': typeof VisualizerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/qa'
    | '/visualizer'
    | '/auth/callback'
    | '/visualizer/$runId'
    | '/visualizer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/qa'
    | '/auth/callback'
    | '/visualizer/$runId'
    | '/visualizer'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/qa'
    | '/visualizer'
    | '/auth/callback'
    | '/visualizer/$runId'
    | '/visualizer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  QaRoute: typeof QaRoute
  VisualizerRoute: typeof VisualizerRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualizer': {
      id: '/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof VisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizer/': {
      id: '/visualizer/'
      path: '/'
      fullPath: '/visualizer/'
      preLoaderRoute: typeof VisualizerIndexRouteImport
      parentRoute: typeof VisualizerRoute
    }
    '/visualizer/$runId': {
      id: '/visualizer/$runId'
      path: '/$runId'
      fullPath: '/visualizer/$runId'
      preLoaderRoute: typeof VisualizerRunIdRouteImport
      parentRoute: typeof VisualizerRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VisualizerRouteChildren {
  VisualizerRunIdRoute: typeof VisualizerRunIdRoute
  VisualizerIndexRoute: typeof VisualizerIndexRoute
}

const VisualizerRouteChildren: VisualizerRouteChildren = {
  VisualizerRunIdRoute: VisualizerRunIdRoute,
  VisualizerIndexRoute: VisualizerIndexRoute,
}

const VisualizerRouteWithChildren = VisualizerRoute._addFileChildren(
  VisualizerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  QaRoute: QaRoute,
  VisualizerRoute: VisualizerRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
