/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizerRouteImport } from './routes/visualizer'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QaRouteImport } from './routes/qa'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualizerIndexRouteImport } from './routes/visualizer.index'
import { Route as VisualizerRunIdRouteImport } from './routes/visualizer.$runId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminVerdictRouteImport } from './routes/admin.verdict'
import { Route as DomainsDomainVisualizerRouteImport } from './routes/domains/$domain/visualizer'
import { Route as DomainsDomainRunsRouteImport } from './routes/domains/$domain/runs'
import { Route as DomainsDomainResearchRouteImport } from './routes/domains/$domain/research'
import { Route as DomainsDomainConfiguratorRouteImport } from './routes/domains/$domain/configurator'
import { Route as ApiPublicStatusRouteImport } from './routes/api.public.status'
import { Route as DomainsDomainVisualizerIdRouteImport } from './routes/domains/$domain/visualizer.$id'
import { Route as DomainsDomainRunsIdRouteImport } from './routes/domains/$domain/runs.$id'

const VisualizerRoute = VisualizerRouteImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizerIndexRoute = VisualizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VisualizerRoute,
} as any)
const VisualizerRunIdRoute = VisualizerRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => VisualizerRoute,
} as any).lazy(() =>
  import('./routes/visualizer.$runId.lazy').then((d) => d.Route),
)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerdictRoute = AdminVerdictRouteImport.update({
  id: '/admin/verdict',
  path: '/admin/verdict',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsDomainVisualizerRoute = DomainsDomainVisualizerRouteImport.update({
  id: '/domains/$domain/visualizer',
  path: '/domains/$domain/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsDomainRunsRoute = DomainsDomainRunsRouteImport.update({
  id: '/domains/$domain/runs',
  path: '/domains/$domain/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsDomainResearchRoute = DomainsDomainResearchRouteImport.update({
  id: '/domains/$domain/research',
  path: '/domains/$domain/research',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsDomainConfiguratorRoute =
  DomainsDomainConfiguratorRouteImport.update({
    id: '/domains/$domain/configurator',
    path: '/domains/$domain/configurator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStatusRoute = ApiPublicStatusRouteImport.update({
  id: '/api/public/status',
  path: '/api/public/status',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsDomainVisualizerIdRoute =
  DomainsDomainVisualizerIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DomainsDomainVisualizerRoute,
  } as any)
const DomainsDomainRunsIdRoute = DomainsDomainRunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DomainsDomainRunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/qa': typeof QaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/visualizer': typeof VisualizerRouteWithChildren
  '/admin/verdict': typeof AdminVerdictRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/visualizer/$runId': typeof VisualizerRunIdRoute
  '/visualizer/': typeof VisualizerIndexRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/domains/$domain/configurator': typeof DomainsDomainConfiguratorRoute
  '/domains/$domain/research': typeof DomainsDomainResearchRoute
  '/domains/$domain/runs': typeof DomainsDomainRunsRouteWithChildren
  '/domains/$domain/visualizer': typeof DomainsDomainVisualizerRouteWithChildren
  '/domains/$domain/runs/$id': typeof DomainsDomainRunsIdRoute
  '/domains/$domain/visualizer/$id': typeof DomainsDomainVisualizerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/qa': typeof QaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/admin/verdict': typeof AdminVerdictRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/visualizer/$runId': typeof VisualizerRunIdRoute
  '/visualizer': typeof VisualizerIndexRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/domains/$domain/configurator': typeof DomainsDomainConfiguratorRoute
  '/domains/$domain/research': typeof DomainsDomainResearchRoute
  '/domains/$domain/runs': typeof DomainsDomainRunsRouteWithChildren
  '/domains/$domain/visualizer': typeof DomainsDomainVisualizerRouteWithChildren
  '/domains/$domain/runs/$id': typeof DomainsDomainRunsIdRoute
  '/domains/$domain/visualizer/$id': typeof DomainsDomainVisualizerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/qa': typeof QaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/visualizer': typeof VisualizerRouteWithChildren
  '/admin/verdict': typeof AdminVerdictRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/visualizer/$runId': typeof VisualizerRunIdRoute
  '/visualizer/': typeof VisualizerIndexRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/domains/$domain/configurator': typeof DomainsDomainConfiguratorRoute
  '/domains/$domain/research': typeof DomainsDomainResearchRoute
  '/domains/$domain/runs': typeof DomainsDomainRunsRouteWithChildren
  '/domains/$domain/visualizer': typeof DomainsDomainVisualizerRouteWithChildren
  '/domains/$domain/runs/$id': typeof DomainsDomainRunsIdRoute
  '/domains/$domain/visualizer/$id': typeof DomainsDomainVisualizerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/qa'
    | '/reset-password'
    | '/status'
    | '/visualizer'
    | '/admin/verdict'
    | '/auth/callback'
    | '/visualizer/$runId'
    | '/visualizer/'
    | '/api/public/status'
    | '/domains/$domain/configurator'
    | '/domains/$domain/research'
    | '/domains/$domain/runs'
    | '/domains/$domain/visualizer'
    | '/domains/$domain/runs/$id'
    | '/domains/$domain/visualizer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/qa'
    | '/reset-password'
    | '/status'
    | '/admin/verdict'
    | '/auth/callback'
    | '/visualizer/$runId'
    | '/visualizer'
    | '/api/public/status'
    | '/domains/$domain/configurator'
    | '/domains/$domain/research'
    | '/domains/$domain/runs'
    | '/domains/$domain/visualizer'
    | '/domains/$domain/runs/$id'
    | '/domains/$domain/visualizer/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pricing'
    | '/qa'
    | '/reset-password'
    | '/status'
    | '/visualizer'
    | '/admin/verdict'
    | '/auth/callback'
    | '/visualizer/$runId'
    | '/visualizer/'
    | '/api/public/status'
    | '/domains/$domain/configurator'
    | '/domains/$domain/research'
    | '/domains/$domain/runs'
    | '/domains/$domain/visualizer'
    | '/domains/$domain/runs/$id'
    | '/domains/$domain/visualizer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  QaRoute: typeof QaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatusRoute: typeof StatusRoute
  VisualizerRoute: typeof VisualizerRouteWithChildren
  AdminVerdictRoute: typeof AdminVerdictRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicStatusRoute: typeof ApiPublicStatusRoute
  DomainsDomainConfiguratorRoute: typeof DomainsDomainConfiguratorRoute
  DomainsDomainResearchRoute: typeof DomainsDomainResearchRoute
  DomainsDomainRunsRoute: typeof DomainsDomainRunsRouteWithChildren
  DomainsDomainVisualizerRoute: typeof DomainsDomainVisualizerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualizer': {
      id: '/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof VisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizer/': {
      id: '/visualizer/'
      path: '/'
      fullPath: '/visualizer/'
      preLoaderRoute: typeof VisualizerIndexRouteImport
      parentRoute: typeof VisualizerRoute
    }
    '/visualizer/$runId': {
      id: '/visualizer/$runId'
      path: '/$runId'
      fullPath: '/visualizer/$runId'
      preLoaderRoute: typeof VisualizerRunIdRouteImport
      parentRoute: typeof VisualizerRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verdict': {
      id: '/admin/verdict'
      path: '/admin/verdict'
      fullPath: '/admin/verdict'
      preLoaderRoute: typeof AdminVerdictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domain/visualizer': {
      id: '/domains/$domain/visualizer'
      path: '/domains/$domain/visualizer'
      fullPath: '/domains/$domain/visualizer'
      preLoaderRoute: typeof DomainsDomainVisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domain/runs': {
      id: '/domains/$domain/runs'
      path: '/domains/$domain/runs'
      fullPath: '/domains/$domain/runs'
      preLoaderRoute: typeof DomainsDomainRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domain/research': {
      id: '/domains/$domain/research'
      path: '/domains/$domain/research'
      fullPath: '/domains/$domain/research'
      preLoaderRoute: typeof DomainsDomainResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domain/configurator': {
      id: '/domains/$domain/configurator'
      path: '/domains/$domain/configurator'
      fullPath: '/domains/$domain/configurator'
      preLoaderRoute: typeof DomainsDomainConfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/status': {
      id: '/api/public/status'
      path: '/api/public/status'
      fullPath: '/api/public/status'
      preLoaderRoute: typeof ApiPublicStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domain/visualizer/$id': {
      id: '/domains/$domain/visualizer/$id'
      path: '/$id'
      fullPath: '/domains/$domain/visualizer/$id'
      preLoaderRoute: typeof DomainsDomainVisualizerIdRouteImport
      parentRoute: typeof DomainsDomainVisualizerRoute
    }
    '/domains/$domain/runs/$id': {
      id: '/domains/$domain/runs/$id'
      path: '/$id'
      fullPath: '/domains/$domain/runs/$id'
      preLoaderRoute: typeof DomainsDomainRunsIdRouteImport
      parentRoute: typeof DomainsDomainRunsRoute
    }
  }
}

interface VisualizerRouteChildren {
  VisualizerRunIdRoute: typeof VisualizerRunIdRoute
  VisualizerIndexRoute: typeof VisualizerIndexRoute
}

const VisualizerRouteChildren: VisualizerRouteChildren = {
  VisualizerRunIdRoute: VisualizerRunIdRoute,
  VisualizerIndexRoute: VisualizerIndexRoute,
}

const VisualizerRouteWithChildren = VisualizerRoute._addFileChildren(
  VisualizerRouteChildren,
)

interface DomainsDomainRunsRouteChildren {
  DomainsDomainRunsIdRoute: typeof DomainsDomainRunsIdRoute
}

const DomainsDomainRunsRouteChildren: DomainsDomainRunsRouteChildren = {
  DomainsDomainRunsIdRoute: DomainsDomainRunsIdRoute,
}

const DomainsDomainRunsRouteWithChildren =
  DomainsDomainRunsRoute._addFileChildren(DomainsDomainRunsRouteChildren)

interface DomainsDomainVisualizerRouteChildren {
  DomainsDomainVisualizerIdRoute: typeof DomainsDomainVisualizerIdRoute
}

const DomainsDomainVisualizerRouteChildren: DomainsDomainVisualizerRouteChildren =
  {
    DomainsDomainVisualizerIdRoute: DomainsDomainVisualizerIdRoute,
  }

const DomainsDomainVisualizerRouteWithChildren =
  DomainsDomainVisualizerRoute._addFileChildren(
    DomainsDomainVisualizerRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  QaRoute: QaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatusRoute: StatusRoute,
  VisualizerRoute: VisualizerRouteWithChildren,
  AdminVerdictRoute: AdminVerdictRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicStatusRoute: ApiPublicStatusRoute,
  DomainsDomainConfiguratorRoute: DomainsDomainConfiguratorRoute,
  DomainsDomainResearchRoute: DomainsDomainResearchRoute,
  DomainsDomainRunsRoute: DomainsDomainRunsRouteWithChildren,
  DomainsDomainVisualizerRoute: DomainsDomainVisualizerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
